//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int Codigo { get; set; }
        public int IDLibro { get; set; }
        public int NroLector { get; set; }
        public System.DateTime Fecha_Prestamo { get; set; }
        public Nullable<System.DateTime> Fecha_Devo { get; set; }
        public System.DateTime Fecha_Estimada { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Libros Libros { get; set; }
    }
}
